// examples/demo/src/react/UserDefinedResponseExample.tsx
/**
 *
 * IBM Confidential
 *
 * (C) Copyright IBM Corp. 2024
 *
 * The source code for this program is not published or otherwise
 * divested of its trade secrets, irrespective of what has been
 * deposited with the U. S. Copyright Office
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *
 */

import "./UserDefinedResponseStyles.css";

import React, { useEffect, useState } from "react";

interface UserDefinedExampleProps {
  text: string;
}

function UserDefinedResponseExample({ text }: UserDefinedExampleProps) {
  const [timestamp, setTimestamp] = useState(0);
  useEffect(() => {
    setInterval(() => {
      setTimestamp(Date.now());
    }, 1000);
  }, []);
  return (
    <div className="external">
      This is a user_defined response type with external styles. The following
      is some text passed along for use by the back-end: {text}. And here is a
      value being set by state: {timestamp}.
    </div>
  );
}

export { UserDefinedResponseExample };

// examples/demo/src/web-components/user-defined-response-example.ts
/**
 *
 * IBM Confidential
 *
 * (C) Copyright IBM Corp. 2024
 *
 * The source code for this program is not published or otherwise
 * divested of its trade secrets, irrespective of what has been
 * deposited with the U. S. Copyright Office
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *
 */

import { css, html, LitElement } from "lit";
import { customElement, property, state } from "lit/decorators.js";

@customElement("user-defined-response-example")
class UserDefinedResponseExample extends LitElement {
  static styles = css`
    .external {
      background: green;
      color: #fff;
      margin-top: 1rem;
      padding: 1rem;
    }
  `;

  @property({ type: String })
  accessor text = "";

  @state()
  accessor timestamp = 0;

  connectedCallback() {
    super.connectedCallback();
    this._startTimer();
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    clearInterval(this._timer);
  }

  private _timer!: ReturnType<typeof setInterval>;

  private _startTimer() {
    this._timer = setInterval(() => {
      this.timestamp = Date.now();
    }, 1000);
  }

  render() {
    return html`
      <div class="external">
        This is a user_defined response type with external styles. The following
        is some text passed along for use by the back-end: ${this.text}. And
        here is a value being set by state: ${this.timestamp}.
      </div>
    `;
  }
}

export default UserDefinedResponseExample;
